# Generated by Django 4.1 on 2022-09-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_usuariosregistro_alter_cliente_edad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuariosRegistro',
        ),
    ]
