# Generated by Django 4.1 on 2022-09-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_usuariosregistro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariosregistro',
            old_name='password1',
            new_name='confirmPassword',
        ),
        migrations.RenameField(
            model_name='usuariosregistro',
            old_name='password2',
            new_name='password',
        ),
    ]
