# Generated by Django 4.1 on 2022-09-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_rename_password1_usuariosregistro_confirmpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosregistro',
            name='confirmPassword',
        ),
    ]
